server:
  port: ${PORT}


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE:ai_travel}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  mvc:
    view:
      suffix: .html
      prefix: /

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

# 微信小程序配置
wechat:
  miniapp:
    app-id: ${WECHAT_APPID}
    app-secret: ${WECHAT_SECRET}
